name: yosina_examples
description: Examples for Yosina Dart library
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yosina:
    path: ..

dev_dependencies:
  lints: ^3.0.0
