name: yosina
description: A transliteration library for Japanese text normalization
version: 0.1.0
homepage: https://github.com/yosina-lib/yosina
repository: https://github.com/yosina-lib/yosina
issue_tracker: https://github.com/yosina-lib/yosina/issues
documentation: https://pub.dev/documentation/yosina/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: any
  archive: ^4.0.0 

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  args: ^2.4.0