import Foundation

enum CodegenError: Error {
    case fileNotFound(String)
    case invalidJSON(String)
    case writeFailed(String)
}

struct CodeGenerator {
    let dataPath: String
    let outputPath: String

    init() {
        let currentPath = FileManager.default.currentDirectoryPath
        dataPath = (currentPath as NSString).appendingPathComponent("../../data")
        outputPath = (currentPath as NSString).appendingPathComponent("../Sources/Yosina/Transliterators")
    }

    func run() throws {
        try FileManager.default.createDirectory(atPath: outputPath, withIntermediateDirectories: true)

        try generateSpacesTransliterator()
        try generateHyphensTransliterator()
        try generateRadicalsTransliterator()
        try generateMathematicalAlphanumericsTransliterator()
        try generateIdeographicAnnotationsTransliterator()
        try generateKanjiOldNewTransliterator()
        try generateCombinedTransliterator()
        try generateCircledOrSquaredTransliterator()
        try generateIvsSvsBaseTransliterator()

        print("Code generation completed successfully!")
    }

    func loadJSONData<T: Decodable>(_ filename: String, as type: T.Type) throws -> T {
        let path = (dataPath as NSString).appendingPathComponent(filename)
        guard let data = FileManager.default.contents(atPath: path) else {
            throw CodegenError.fileNotFound(filename)
        }

        do {
            return try JSONDecoder().decode(type, from: data)
        } catch {
            throw CodegenError.invalidJSON("\(filename): \(error)")
        }
    }

    func writeFile(_ filename: String, content: String) throws {
        let path = (outputPath as NSString).appendingPathComponent(filename)
        do {
            try content.write(toFile: path, atomically: true, encoding: .utf8)
        } catch {
            throw CodegenError.writeFailed("\(filename): \(error)")
        }
    }

    func fileHeader() -> String {
        """
        // This file is automatically generated. Do not edit.
        // Generated on: \(Date())

        import Foundation

        """
    }
}

// MARK: - Spaces Transliterator

extension CodeGenerator {
    func generateSpacesTransliterator() throws {
        let data = try loadJSONData("spaces.json", as: [String: String?].self)

        var content = fileHeader()
        content += """
        public struct SpacesTransliterator: Transliterator {
            private let mapping: [String: String]

            public init() {
                var dict: [String: String] = [:]
        """

        let sortedPairs = data.sorted { $0.key < $1.key }
        for (key, value) in sortedPairs {
            guard let value = value else { continue }
            let fromChar = unicodeToChar(key)
            let toChar = unicodeToChar(value)
            content += "\n        dict[\"\(escape(fromChar))\"] = \"\(escape(toChar))\""
        }

        content += """

                self.mapping = dict
            }

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset: Int = 0

                for char in chars {
                    if let replacement = mapping[char.value] {
                        let c = TransliteratorChar(value: replacement, offset: offset, source: char)
                        offset += replacement.count
                        result.append(c);
                    } else {
                        let char = char.withOffset(offset)
                        offset += char.value.count
                        result.append(char)
                    }
                }

                return result
            }
        }
        """

        try writeFile("SpacesTransliterator.swift", content: content)
        print("Generated SpacesTransliterator.swift")
    }
}

// MARK: - Hyphens Transliterator

extension CodeGenerator {
    struct HyphenData: Codable {
        let code: String
        let name: String
        let ascii: [String]?
        let jisx0201: [String]?
        let jisx0208_1978: [String]? // Maps to jisx0208_90
        let jisx0208_1978_windows: [String]? // Maps to jisx0208_90_windows
        let jisx0208_verbatim: StringOrArray? // Can be string or null in JSON

        enum CodingKeys: String, CodingKey {
            case code, name, ascii, jisx0201
            case jisx0208_1978 = "jisx0208-1978"
            case jisx0208_1978_windows = "jisx0208-1978-windows"
            case jisx0208_verbatim = "jisx0208-verbatim"
        }
    }

    enum StringOrArray: Codable {
        case string(String)
        case array([String])

        init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let value = try? container.decode(String.self) {
                self = .string(value)
            } else if let value = try? container.decode([String].self) {
                self = .array(value)
            } else {
                throw DecodingError.typeMismatch(StringOrArray.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Expected String or [String]"))
            }
        }

        func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case let .string(value):
                try container.encode(value)
            case let .array(value):
                try container.encode(value)
            }
        }

        var asArray: [String]? {
            switch self {
            case let .string(value):
                return [value]
            case let .array(value):
                return value
            }
        }
    }

    func generateHyphensTransliterator() throws {
        let dataArray = try loadJSONData("hyphens.json", as: [HyphenData].self)

        var content = fileHeader()
        content += """
        public struct HyphensTransliterator: Transliterator {
            public enum Precedence: String, CaseIterable {
                case ascii
                case jisx0201
                case jisx0208_90
                case jisx0208_90_windows
                case jisx0208_verbatim
            }

            public struct Options {
                public var precedence: [Precedence] = [.jisx0208_90]

                public init() {}
            }

            private struct HyphensRecord {
                let ascii: String?
                let jisx0201: String?
                let jisx0208_90: String?
                let jisx0208_90_windows: String?
                let jisx0208_verbatim: String?
            }

            private let options: Options
            private let mapping: [String: HyphensRecord] = [
        """

        for item in dataArray {
            let fromChar = unicodeToChar(item.code)

            // Handle multi-character replacements
            let ascii = item.ascii?.map { unicodeToChar($0) }.joined(separator: "")
            let jisx0201 = item.jisx0201?.map { unicodeToChar($0) }.joined(separator: "")
            let jisx0208_90 = item.jisx0208_1978?.map { unicodeToChar($0) }.joined(separator: "")
            let jisx0208_90_windows = item.jisx0208_1978_windows?.map { unicodeToChar($0) }.joined(separator: "")
            let jisx0208_verbatim = item.jisx0208_verbatim?.asArray?.map { unicodeToChar($0) }.joined(separator: "")

            content += "\n        \"\(escape(fromChar))\": HyphensRecord("
            content += "\n            ascii: " + (ascii != nil ? "\"\(escape(ascii!))\"" : "nil") + ","
            content += "\n            jisx0201: " + (jisx0201 != nil ? "\"\(escape(jisx0201!))\"" : "nil") + ","
            content += "\n            jisx0208_90: " + (jisx0208_90 != nil ? "\"\(escape(jisx0208_90!))\"" : "nil") + ","
            content += "\n            jisx0208_90_windows: " + (jisx0208_90_windows != nil ? "\"\(escape(jisx0208_90_windows!))\"" : "nil") + ","
            content += "\n            jisx0208_verbatim: " + (jisx0208_verbatim != nil ? "\"\(escape(jisx0208_verbatim!))\"" : "nil")
            content += "\n        ),"
        }

        content += """

            ]

            public init(options: Options = Options()) {
                self.options = options
            }

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset = 0

                for char in chars {
                    if let record = mapping[char.value] {
                        let replacement = getReplacement(for: record)
                        if let replacement = replacement, replacement != char.value {
                            // Handle multi-character replacements
                            for replacementChar in replacement {
                                let c = TransliteratorChar(
                                    value: String(replacementChar),
                                    offset: offset,
                                    source: char
                                )
                                result.append(c)
                                offset += String(replacementChar).count
                            }
                            continue
                        }
                    }
                    let char = char.withOffset(offset)
                    offset += char.value.count
                    result.append(char)
                }

                return result
            }

            private func getReplacement(for record: HyphensRecord) -> String? {
                for prec in options.precedence {
                    switch prec {
                    case .ascii:
                        if let replacement = record.ascii { return replacement }
                    case .jisx0201:
                        if let replacement = record.jisx0201 { return replacement }
                    case .jisx0208_90:
                        if let replacement = record.jisx0208_90 { return replacement }
                    case .jisx0208_90_windows:
                        if let replacement = record.jisx0208_90_windows { return replacement }
                    case .jisx0208_verbatim:
                        if let replacement = record.jisx0208_verbatim { return replacement }
                    }
                }
                return nil
            }
        }
        """

        try writeFile("HyphensTransliterator.swift", content: content)
        print("Generated HyphensTransliterator.swift")
    }
}

// MARK: - Other Transliterators (simplified for brevity)

extension CodeGenerator {
    func generateRadicalsTransliterator() throws {
        try generateSimpleMapping("radicals.json", className: "RadicalsTransliterator")
    }

    func generateMathematicalAlphanumericsTransliterator() throws {
        try generateSimpleMapping("mathematical-alphanumerics.json", className: "MathematicalAlphanumericsTransliterator")
    }

    func generateIdeographicAnnotationsTransliterator() throws {
        try generateSimpleMapping("ideographic-annotation-marks.json", className: "IdeographicAnnotationsTransliterator")
    }

    struct KanjiVariant: Codable {
        let ivs: [String]?
        let svs: [String]?
    }

    func generateKanjiOldNewTransliterator() throws {
        let data = try loadJSONData("kanji-old-new-form.json", as: [[KanjiVariant]].self)

        var content = fileHeader()
        content += """
        public struct KanjiOldNewTransliterator: Transliterator {
            private let mapping: [String: String] = [
        """

        var mappings: [String: String] = [:]

        for pair in data {
            guard pair.count >= 2 else { continue }
            let oldForm = pair[0]
            let newForm = pair[1]

            if let oldIvs = oldForm.ivs, oldIvs.count >= 1,
               let newIvs = newForm.ivs, newIvs.count >= 1
            {
                let oldChar = unicodeToChar(oldIvs[0])
                let newChar = unicodeToChar(newIvs[0])
                mappings[oldChar] = newChar
            } else if let oldSvs = oldForm.svs, oldSvs.count >= 1,
                      let newSvs = newForm.svs, newSvs.count >= 1
            {
                let oldChar = unicodeToChar(oldSvs[0])
                let newChar = unicodeToChar(newSvs[0])
                mappings[oldChar] = newChar
            }
        }

        let sortedPairs = mappings.sorted { $0.key < $1.key }
        for (key, value) in sortedPairs {
            content += "\n        \"\(escape(key))\": \"\(escape(value))\","
        }

        content += """

            ]

            public init() {}

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset = 0

                for char in chars {
                    if let replacement = mapping[char.value] {
                        let char = TransliteratorChar(value: replacement, offset: offset, source: char)
                        offset += replacement.count
                        result.append(char)
                    } else {
                        let char = char.withOffset(offset)
                        offset += char.value.count
                        result.append(char)
                    }
                }

                return result
            }
        }
        """

        try writeFile("KanjiOldNewTransliterator.swift", content: content)
        print("Generated KanjiOldNewTransliterator.swift")
    }

    func generateSimpleMapping(_ jsonFile: String, className: String) throws {
        let data = try loadJSONData(jsonFile, as: [String: String].self)

        var content = fileHeader()
        content += """
        public struct \(className): Transliterator {
            private let mapping: [String: String] = [
        """

        let sortedPairs = data.sorted { $0.key < $1.key }
        for (key, value) in sortedPairs {
            let fromChar = unicodeToChar(key)
            let toChar = unicodeToChar(value)
            content += "\n        \"\(escape(fromChar))\": \"\(escape(toChar))\","
        }

        content += """

            ]

            public init() {}

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset = 0

                for char in chars {
                    if let replacement = mapping[char.value] {
                        let char = TransliteratorChar(value: replacement, offset: offset, source: char)
                        offset += replacement.count 
                        result.append(char)
                    } else {
                        let char = char.withOffset(offset)
                        offset += char.value.count 
                        result.append(char)
                    }
                }

                return result
            }
        }
        """

        try writeFile("\(className).swift", content: content)
        print("Generated \(className).swift")
    }
}

// MARK: - Combined Transliterator

extension CodeGenerator {
    func generateCombinedTransliterator() throws {
        let data = try loadJSONData("combined-chars.json", as: [String: String].self)

        var content = fileHeader()
        content += """
        public struct CombinedTransliterator: Transliterator {
            private let mapping: [String: [String]] = [
        """

        let sortedPairs = data.sorted { $0.key < $1.key }
        for (key, value) in sortedPairs {
            let fromChar = unicodeToChar(key)
            // Split the replacement string into individual characters
            let replacementChars = value.map { "\"\(escape(String($0)))\"" }.joined(separator: ", ")
            content += "\n        \"\(escape(fromChar))\": [\(replacementChars)],"
        }

        content += """

            ]

            public init() {}

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset = 0

                for char in chars {
                    if let replacements = mapping[char.value] {
                        for replacement in replacements {
                            let char = TransliteratorChar(
                                value: replacement,
                                offset: offset,
                                source: char
                            )
                            offset += replacement.count
                            result.append(char)
                        }
                    } else {
                        let char = char.withOffset(offset)
                        offset += char.value.count
                        result.append(char)
                    }
                }

                return result
            }
        }
        """

        try writeFile("CombinedTransliterator.swift", content: content)
        print("Generated CombinedTransliterator.swift")
    }
}

// MARK: - Circled or Squared Transliterator

extension CodeGenerator {
    struct CircledOrSquaredEntry: Decodable {
        let rendering: String
        let type: String
        let isEmoji: Bool

        enum CodingKeys: String, CodingKey {
            case rendering, type, emoji
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            rendering = try container.decode(String.self, forKey: .rendering)
            type = try container.decode(String.self, forKey: .type)

            // Handle both Bool and String for emoji field
            if let boolValue = try? container.decode(Bool.self, forKey: .emoji) {
                isEmoji = boolValue
            } else if let stringValue = try? container.decode(String.self, forKey: .emoji) {
                isEmoji = stringValue == "true"
            } else {
                isEmoji = false
            }
        }
    }

    func generateCircledOrSquaredTransliterator() throws {
        let data = try loadJSONData("circled-or-squared.json", as: [String: CircledOrSquaredEntry].self)

        var content = fileHeader()
        content += """
        public struct CircledOrSquaredTransliterator: Transliterator {
            public struct Options {
                public var includeEmojis: Bool = true
                public var circleTemplate: String = "(?)"
                public var squareTemplate: String = "[?]"

                public init() {}
            }

            private struct Entry {
                let rendering: String
                let type: String
                let isEmoji: Bool
            }

            private let options: Options
            private let mapping: [String: Entry] = [
        """

        let sortedPairs = data.sorted { $0.key < $1.key }
        for (key, entry) in sortedPairs {
            let fromChar = unicodeToChar(key)
            content += "\n        \"\(escape(fromChar))\": Entry(rendering: \"\(escape(entry.rendering))\", type: \"\(entry.type)\", isEmoji: \(entry.isEmoji)),"
        }

        content += """

            ]

            public init(options: Options = Options()) {
                self.options = options
            }

            public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
                var result: [TransliteratorChar] = []
                var offset = 0

                for char in chars {
                    if let entry = mapping[char.value] {
                        if !options.includeEmojis && entry.isEmoji {
                            result.append(char)
                        } else {
                            let template = entry.type == "circle" ? options.circleTemplate : options.squareTemplate
                            let replacement = template.replacingOccurrences(of: "?", with: entry.rendering)
                            let char = TransliteratorChar(value: replacement, offset: offset, source: char)
                            offset += replacement.count
                            result.append(char)
                        }
                    } else {
                        let char = char.withOffset(offset)
                        offset += char.value.count
                        result.append(char)
                    }
                }

                return result
            }
        }
        """

        try writeFile("CircledOrSquaredTransliterator.swift", content: content)
        print("Generated CircledOrSquaredTransliterator.swift")
    }
}

// MARK: - IVS/SVS Base Transliterator

extension CodeGenerator {
    struct IvsSvsMapping: Codable {
        let ivs: [String]?
        let svs: [String]?
        let base90: String?
        let base2004: String?
    }

    func generateIvsSvsBaseTransliterator() throws {
        // Generate the binary data file
        let jsonPath = (dataPath as NSString).appendingPathComponent("ivs-svs-base-mappings.json")
        let resourcesPath = (outputPath as NSString).deletingLastPathComponent.appending("/Resources")
        try FileManager.default.createDirectory(atPath: resourcesPath, withIntermediateDirectories: true)
        let dataPath = (resourcesPath as NSString).appendingPathComponent("ivs_svs_base.data")

        try IvsSvsBaseDataGenerator.generate(from: jsonPath, to: dataPath)

        // Write the transliterator source file (no embedded data)
        // This is already done - the IvsSvsBaseTransliterator.swift now loads from the binary data file
        print("Generated ivs_svs_base.data")
    }
}

// MARK: - Helper Functions

func escape(_ string: String) -> String {
    return string
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
        .replacingOccurrences(of: "\r", with: "\\r")
        .replacingOccurrences(of: "\t", with: "\\t")
}

func unicodeToChar(_ unicode: String) -> String {
    // Handle "U+XXXX" format
    if unicode.hasPrefix("U+") {
        let hex = String(unicode.dropFirst(2))
        if let codePoint = Int(hex, radix: 16),
           let scalar = UnicodeScalar(codePoint)
        {
            return String(scalar)
        }
    }
    return unicode
}

// MARK: - Main

do {
    let generator = CodeGenerator()
    try generator.run()
} catch {
    print("Error: \(error)")
    exit(1)
}
