// This file is automatically generated. Do not edit.
// Generated on: 2025-08-14 00:38:21 +0000

import Foundation

public struct HyphensTransliterator: Transliterator {
    public enum Precedence: String, CaseIterable {
        case ascii
        case jisx0201
        case jisx0208_90
        case jisx0208_90_windows
        case jisx0208_verbatim
    }

    public struct Options {
        public var precedence: [Precedence] = [.jisx0208_90]

        public init() {}
    }

    private struct HyphensRecord {
        let ascii: String?
        let jisx0201: String?
        let jisx0208_90: String?
        let jisx0208_90_windows: String?
        let jisx0208_verbatim: String?
    }

    private let options: Options
    private let mapping: [String: HyphensRecord] = [
        "-": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "−",
            jisx0208_90_windows: "−",
            jisx0208_verbatim: nil
        ),
        "|": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: nil
        ),
        "~": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "～",
            jisx0208_verbatim: nil
        ),
        "¢": HyphensRecord(
            ascii: nil,
            jisx0201: nil,
            jisx0208_90: "¢",
            jisx0208_90_windows: "￠",
            jisx0208_verbatim: "¢"
        ),
        "£": HyphensRecord(
            ascii: nil,
            jisx0201: nil,
            jisx0208_90: "£",
            jisx0208_90_windows: "￡",
            jisx0208_verbatim: "£"
        ),
        "¦": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: "¦"
        ),
        "˗": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "−",
            jisx0208_90_windows: "－",
            jisx0208_verbatim: nil
        ),
        "‐": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "‐",
            jisx0208_verbatim: "‐"
        ),
        "‑": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "‐",
            jisx0208_verbatim: nil
        ),
        "‒": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "―",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: nil
        ),
        "–": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "―",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: "–"
        ),
        "—": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "—",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: "—"
        ),
        "―": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "―",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: "―"
        ),
        "‖": HyphensRecord(
            ascii: nil,
            jisx0201: nil,
            jisx0208_90: "‖",
            jisx0208_90_windows: "∥",
            jisx0208_verbatim: "‖"
        ),
        "‾": HyphensRecord(
            ascii: nil,
            jisx0201: "~",
            jisx0208_90: "￣",
            jisx0208_90_windows: "￣",
            jisx0208_verbatim: "‽"
        ),
        "⁃": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "‐",
            jisx0208_verbatim: nil
        ),
        "⁓": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "〜",
            jisx0208_verbatim: nil
        ),
        "−": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "−",
            jisx0208_90_windows: "－",
            jisx0208_verbatim: "−"
        ),
        "∥": HyphensRecord(
            ascii: nil,
            jisx0201: nil,
            jisx0208_90: "‖",
            jisx0208_90_windows: "∥",
            jisx0208_verbatim: "∥"
        ),
        "∼": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "～",
            jisx0208_verbatim: nil
        ),
        "∽": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "～",
            jisx0208_verbatim: nil
        ),
        "─": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "―",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: "─"
        ),
        "━": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "―",
            jisx0208_90_windows: "―",
            jisx0208_verbatim: "━"
        ),
        "│": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: "│"
        ),
        "➖": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "−",
            jisx0208_90_windows: "－",
            jisx0208_verbatim: nil
        ),
        "⧿": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "－",
            jisx0208_verbatim: nil
        ),
        "⸺": HyphensRecord(
            ascii: "--",
            jisx0201: "--",
            jisx0208_90: "——",
            jisx0208_90_windows: "――",
            jisx0208_verbatim: nil
        ),
        "⸻": HyphensRecord(
            ascii: "---",
            jisx0201: "---",
            jisx0208_90: "———",
            jisx0208_90_windows: "―――",
            jisx0208_verbatim: nil
        ),
        "〜": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "～",
            jisx0208_verbatim: "〜"
        ),
        "゠": HyphensRecord(
            ascii: "=",
            jisx0201: "=",
            jisx0208_90: "＝",
            jisx0208_90_windows: "＝",
            jisx0208_verbatim: "゠"
        ),
        "・": HyphensRecord(
            ascii: nil,
            jisx0201: "･",
            jisx0208_90: "・",
            jisx0208_90_windows: "・",
            jisx0208_verbatim: "・"
        ),
        "ー": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "ー",
            jisx0208_90_windows: "ー",
            jisx0208_verbatim: "ー"
        ),
        "︱": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: nil
        ),
        "﹘": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "‐",
            jisx0208_verbatim: nil
        ),
        "﹣": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "‐",
            jisx0208_90_windows: "‐",
            jisx0208_verbatim: nil
        ),
        "－": HyphensRecord(
            ascii: "-",
            jisx0201: "-",
            jisx0208_90: "−",
            jisx0208_90_windows: "－",
            jisx0208_verbatim: nil
        ),
        "｜": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: "｜"
        ),
        "～": HyphensRecord(
            ascii: "~",
            jisx0201: "~",
            jisx0208_90: "〜",
            jisx0208_90_windows: "～",
            jisx0208_verbatim: nil
        ),
        "￤": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "￤",
            jisx0208_verbatim: "￤"
        ),
        "ｰ": HyphensRecord(
            ascii: "-",
            jisx0201: "ｰ",
            jisx0208_90: "ー",
            jisx0208_90_windows: "ー",
            jisx0208_verbatim: nil
        ),
        "￨": HyphensRecord(
            ascii: "|",
            jisx0201: "|",
            jisx0208_90: "｜",
            jisx0208_90_windows: "｜",
            jisx0208_verbatim: nil
        ),
    ]

    public init(options: Options = Options()) {
        self.options = options
    }

    public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
        var result: [TransliteratorChar] = []
        var offset = 0

        for char in chars {
            if let record = mapping[char.value] {
                let replacement = getReplacement(for: record)
                if let replacement = replacement, replacement != char.value {
                    // Handle multi-character replacements
                    for replacementChar in replacement {
                        let c = TransliteratorChar(
                            value: String(replacementChar),
                            offset: offset,
                            source: char
                        )
                        result.append(c)
                        offset += String(replacementChar).count
                    }
                    continue
                }
            }
            let char = char.withOffset(offset)
            offset += char.value.count
            result.append(char)
        }

        return result
    }

    private func getReplacement(for record: HyphensRecord) -> String? {
        for prec in options.precedence {
            switch prec {
            case .ascii:
                if let replacement = record.ascii { return replacement }
            case .jisx0201:
                if let replacement = record.jisx0201 { return replacement }
            case .jisx0208_90:
                if let replacement = record.jisx0208_90 { return replacement }
            case .jisx0208_90_windows:
                if let replacement = record.jisx0208_90_windows { return replacement }
            case .jisx0208_verbatim:
                if let replacement = record.jisx0208_verbatim { return replacement }
            }
        }
        return nil
    }
}
