// This file is automatically generated. Do not edit.
// Generated on: 2025-08-14 00:38:21 +0000

import Foundation

public struct IdeographicAnnotationsTransliterator: Transliterator {
    private let mapping: [String: String] = [
        "㆒": "一",
        "㆓": "二",
        "㆔": "三",
        "㆕": "四",
        "㆖": "上",
        "㆗": "中",
        "㆘": "下",
        "㆙": "甲",
        "㆚": "乙",
        "㆛": "丙",
        "㆜": "丁",
        "㆝": "天",
        "㆞": "地",
        "㆟": "人",
    ]

    public init() {}

    public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
        var result: [TransliteratorChar] = []
        var offset = 0

        for char in chars {
            if let replacement = mapping[char.value] {
                let char = TransliteratorChar(value: replacement, offset: offset, source: char)
                offset += replacement.count
                result.append(char)
            } else {
                let char = char.withOffset(offset)
                offset += char.value.count
                result.append(char)
            }
        }

        return result
    }
}
