// This file is automatically generated. Do not edit.
// Generated on: 2025-08-14 00:38:21 +0000

import Foundation

public struct SpacesTransliterator: Transliterator {
    private let mapping: [String: String]

    public init() {
        var dict: [String: String] = [:]
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict["​"] = " "
        dict[" "] = " "
        dict[" "] = " "
        dict["　"] = " "
        dict["ㅤ"] = " "
        dict["ﾠ"] = " "
        mapping = dict
    }

    public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
        var result: [TransliteratorChar] = []
        var offset = 0

        for char in chars {
            if let replacement = mapping[char.value] {
                let c = TransliteratorChar(value: replacement, offset: offset, source: char)
                offset += replacement.count
                result.append(c)
            } else {
                let char = char.withOffset(offset)
                offset += char.value.count
                result.append(char)
            }
        }

        return result
    }
}
